from vvspy.models.arrival import Arrival
from vvspy.models.connection import Connection
from vvspy.models.departure import Departure
from vvspy.models.destination import Destination
from vvspy.models.line_operator import LineOperator
from vvspy.models.origin import Origin
from vvspy.models.serving_line import ServingLine
from vvspy.models.transportation import Transportation
from vvspy.models.trip import Trip
